extends:
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/no-unused-expressions': off
  '@typescript-eslint/no-unused-vars':
    argsIgnorePattern: ^_
    caughtErrorsIgnorePattern: ^_
    destructuredArrayIgnorePattern: ^_
    varsIgnorePattern: ^_
